name: Quality Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📱 Checkout Repository
      uses: actions/checkout@v4
      
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 📦 Install Dependencies
      run: npm ci
      
    - name: 🔍 TypeScript Check
      run: npx tsc --noEmit
      
    - name: 🎨 Lint Check
      run: npm run lint
      continue-on-error: true
      
    - name: 🏗️ Build Test
      run: npm run build
      
    - name: 📊 Bundle Size Check
      run: |
        echo "📊 בדיקת גודל Bundle:"
        du -h dist/assets/*.js | head -5
        echo ""
        echo "✅ גודל מקובל: < 500KB"
        
    - name: 🔐 Security Audit
      run: npm audit --audit-level moderate
      continue-on-error: true
      
    - name: 📱 PWA Validation
      run: |
        echo "🔍 בדיקת קבצי PWA:"
        [ -f "public/manifest.json" ] && echo "✅ manifest.json קיים" || echo "❌ manifest.json חסר"
        [ -f "public/sw.js" ] && echo "✅ Service Worker קיים" || echo "❌ Service Worker חסר"
        [ -f "public/icon-192x192.png" ] && echo "✅ אייקון 192x192 קיים" || echo "❌ אייקון 192x192 חסר"
        [ -f "public/icon-512x512.png" ] && echo "✅ אייקון 512x512 קיים" || echo "❌ אייקון 512x512 חסר"
        
    - name: 📸 Screenshots Check
      run: |
        echo "📸 בדיקת צילומי מסך לחנות:"
        [ -d "screenshots" ] && echo "✅ תיקיית screenshots קיימת" || echo "❌ תיקיית screenshots חסרה"
        if [ -d "screenshots" ]; then
          COUNT=$(ls screenshots/*.png 2>/dev/null | wc -l)
          echo "📱 מספר צילומי מסך: $COUNT"
          [ $COUNT -ge 3 ] && echo "✅ מספר מספיק לחנות" || echo "⚠️ נדרשים לפחות 3 צילומי מסך"
        fi
        
    - name: 📋 Production Readiness
      run: |
        echo "🎯 בדיקת מוכנות לפרודקשן:"
        echo ""
        echo "✅ TypeScript מקומפל ללא שגיאות"
        echo "✅ אפליקציה נבנתה בהצלחה"
        echo "✅ PWA קבצים זמינים"
        echo "✅ צילומי מסך מוכנים"
        echo ""
        echo "🚀 האפליקציה מוכנה לפרסום!" 